(ns year2021.day14.day14-data)

(def day14-example "NNCB\n\nCH -> B\nHH -> N\nCB -> H\nNH -> C\nHB -> C\nHC -> B\nHN -> C\nNN -> C\nBH -> H\nNC -> B\nNB -> B\nBN -> B\nBB -> N\nBC -> B\nCC -> N\nCN -> C")
;NNCB
;
;CH -> B
;HH -> N
;CB -> H
;NH -> C
;HB -> C
;HC -> B
;HN -> C
;NN -> C
;BH -> H
;NC -> B
;NB -> B
;BN -> B
;BB -> N
;BC -> B
;CC -> N
;CN -> C

(def day14-puzzle "SFBBNKKOHHHPFOFFSPFV\n\nHB -> C\nKO -> S\nKK -> N\nPF -> F\nVB -> F\nKC -> S\nBP -> H\nSS -> H\nBS -> B\nPB -> O\nVH -> C\nBK -> S\nBO -> F\nHN -> V\nNN -> K\nPV -> C\nNH -> P\nKP -> N\nNB -> V\nNF -> V\nPP -> O\nPN -> B\nVN -> K\nSC -> O\nNS -> N\nSV -> B\nBV -> P\nFV -> F\nOK -> H\nHF -> F\nCV -> K\nKB -> C\nOB -> B\nNO -> V\nOF -> B\nHP -> C\nBB -> F\nFB -> H\nOC -> K\nNV -> H\nOV -> S\nOP -> N\nSP -> N\nFK -> F\nVV -> B\nVK -> H\nOS -> F\nCO -> F\nCH -> V\nHV -> V\nFN -> B\nCS -> F\nPS -> F\nHS -> F\nVO -> K\nNP -> F\nFP -> B\nKF -> P\nCC -> N\nBF -> S\nVP -> F\nHO -> H\nFC -> F\nBH -> K\nNK -> S\nBN -> V\nSH -> K\nCP -> B\nVS -> K\nON -> S\nFS -> P\nHK -> F\nPC -> O\nKN -> H\nCK -> N\nHH -> N\nCN -> S\nBC -> K\nPH -> N\nOO -> B\nFO -> O\nSK -> B\nFF -> V\nVC -> N\nSF -> N\nKH -> V\nSO -> F\nKS -> H\nSB -> K\nVF -> V\nPK -> O\nOH -> N\nHC -> F\nPO -> O\nNC -> F\nFH -> V\nKV -> V\nCB -> C\nCF -> O\nSN -> H")
;SFBBNKKOHHHPFOFFSPFV
;
;HB -> C
;KO -> S
;KK -> N
;PF -> F
;VB -> F
;KC -> S
;BP -> H
;SS -> H
;BS -> B
;PB -> O
;VH -> C
;BK -> S
;BO -> F
;HN -> V
;NN -> K
;PV -> C
;NH -> P
;KP -> N
;NB -> V
;NF -> V
;PP -> O
;PN -> B
;VN -> K
;SC -> O
;NS -> N
;SV -> B
;BV -> P
;FV -> F
;OK -> H
;HF -> F
;CV -> K
;KB -> C
;OB -> B
;NO -> V
;OF -> B
;HP -> C
;BB -> F
;FB -> H
;OC -> K
;NV -> H
;OV -> S
;OP -> N
;SP -> N
;FK -> F
;VV -> B
;VK -> H
;OS -> F
;CO -> F
;CH -> V
;HV -> V
;FN -> B
;CS -> F
;PS -> F
;HS -> F
;VO -> K
;NP -> F
;FP -> B
;KF -> P
;CC -> N
;BF -> S
;VP -> F
;HO -> H
;FC -> F
;BH -> K
;NK -> S
;BN -> V
;SH -> K
;CP -> B
;VS -> K
;ON -> S
;FS -> P
;HK -> F
;PC -> O
;KN -> H
;CK -> N
;HH -> N
;CN -> S
;BC -> K
;PH -> N
;OO -> B
;FO -> O
;SK -> B
;FF -> V
;VC -> N
;SF -> N
;KH -> V
;SO -> F
;KS -> H
;SB -> K
;VF -> V
;PK -> O
;OH -> N
;HC -> F
;PO -> O
;NC -> F
;FH -> V
;KV -> V
;CB -> C
;CF -> O
;SN -> H